### ISSUE TITLE
ezy.sdk3rd.3rd-alipay ezy.sdk3rd.3rd-qq 折两个单独出来的库是什么用意

### ISSUE THREAD

**Issue by kamaelyoung** [czy1121/sdk3rd#1]
ezy.sdk3rd.3rd-alipay ezy.sdk3rd.3rd-qq 折两个单独出来的库是什么用意

**Comment by ByteRax** [comment]
@kamaelyoung  有些人只需要QQ或者alipay

**Comment by czy1121** [comment]
这主要因为alipay和qq没有提供maven库所自己封装了一个
里没并没有添加额外的代码或资源
你如果不喜欢自己引入也可以

**Comment by kamaelyoung** [comment]
谢谢回复。 已经合并到一个库里面了。
